//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartPrintScreenMobile {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartPrintScreenMobile.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartScreenShot.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear list.
        /// </summary>
        public static string ClearList {
            get {
                return ResourceManager.GetString("ClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear URLs list?.
        /// </summary>
        public static string ClearListQ {
            get {
                return ResourceManager.GetString("ClearListQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied URLs list to clipboard.
        /// </summary>
        public static string CopiedList {
            get {
                return ResourceManager.GetString("CopiedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied screenshot URL to clipboard.
        /// </summary>
        public static string CopiedToClipboardToast {
            get {
                return ResourceManager.GetString("CopiedToClipboardToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy list.
        /// </summary>
        public static string CopyList {
            get {
                return ResourceManager.GetString("CopyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy URL.
        /// </summary>
        public static string CopyURL {
            get {
                return ResourceManager.GetString("CopyURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete URL.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this screenshot URL?.
        /// </summary>
        public static string DeleteQ {
            get {
                return ResourceManager.GetString("DeleteQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list is empty :(
        ///
        ///Hold down &quot;Power&quot;+&quot;Volume Down&quot;
        ///to capture a screenshot.
        /// </summary>
        public static string EmptyList {
            get {
                return ResourceManager.GetString("EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured,
        ///check your internet connection.
        /// </summary>
        public static string ErrorCheckConnection {
            get {
                return ResourceManager.GetString("ErrorCheckConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a screenshot from storage after uploading.
        /// </summary>
        public static string RemoveShots {
            get {
                return ResourceManager.GetString("RemoveShots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartScreenShot requires a permission
        ///to read from external storage.
        /// </summary>
        public static string RequestRead {
            get {
                return ResourceManager.GetString("RequestRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartScreenShot requires a permission
        ///to write to external storage.
        /// </summary>
        public static string RequestWrite {
            get {
                return ResourceManager.GetString("RequestWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot.
        /// </summary>
        public static string Screenshot {
            get {
                return ResourceManager.GetString("Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start on device boot.
        /// </summary>
        public static string StartOnBoot {
            get {
                return ResourceManager.GetString("StartOnBoot", resourceCulture);
            }
        }
    }
}
